services:
  rabbitmq:
    image: 'rabbitmq:4-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=myuser'
      - 'RABBITMQ_DEFAULT_PASS=secret'
    ports:
      - '5672:5672'
      - '15672:15672'
